### ISSUE TITLE
Bible Acrostic -> Levitecus

### ISSUE THREAD

**Issue by Vehmloewff** [TehShrike/memorize-text-app#11]
When I navigate to **Bible Acrostic -> Levitecus** the memorize page does not load.  The app throws an error and will not work again until I clear the site data and reload.

I tried all the other Bible Acrostics on https://memorizetext.com/#/workbook/1OX4eS10MxNQbgfMzIZx2IEeivq6dGOc_F8X3IraMNds/select for this error and found there to only be a problem with Levitecus.

**Comment by Vehmloewff** [comment]
This might be it: 
[Here](https://docs.google.com/spreadsheets/d/e/2PACX-1vS1Opzrcg4k8P3-8or0QBVFXdqa03yOLBGr40JEy1xP2H7y3RU-rMbhmXKCifuTQ4mHkAFa0RW3X42T/pubhtml#) -> Levitecus

**Comment by TehShrike** [comment]
All righty, I fixed the data in the spreadsheet - I'll open a new issue for the poor UI
