### ISSUE TITLE
Memorization text appearing in header

### ISSUE THREAD

**Issue by Vehmloewff** [TehShrike/memorize-text-app#12]
https://memorizetext.com/#/workbook/1OX4eS10MxNQbgfMzIZx2IEeivq6dGOc_F8X3IraMNds/sheet/ocgfcqb/memorize

At the link above, it looks like some of the memorization content is appearing in the header.

**Comment by TehShrike** [comment]
Good catch, that was bad data in [the document](https://docs.google.com/spreadsheets/d/1OX4eS10MxNQbgfMzIZx2IEeivq6dGOc_F8X3IraMNds/edit#gid=753184745).  I fixed it.
