### ISSUE TITLE
The header on the select sheet could stand to be centered

### ISSUE THREAD

**Issue by Vehmloewff** [TehShrike/memorize-text-app#16]
This is what the select sheet looks like when there is a short word in the header:
![screen shot 2019-02-07 at 2 32 22 pm](https://user-images.githubusercontent.com/45398751/52441446-36198e80-2ae6-11e9-9d35-95becaf6a063.png)

Because the page is centered, it gives things a weird look to have the header not centered.

**Comment by TehShrike** [comment]
👍
