### ISSUE TITLE
Nothing visible to the user happens if the google link is wrong

### ISSUE THREAD

**Issue by Vehmloewff** [TehShrike/memorize-text-app#23]
Right now, if a user were to paste a google link into the `SpeadSheetInput` component, if the link is not correct, nothing visible to the user happens, it just throws a bunch of errors to the console.

This could lead to a very frustrating user experience!

If the url is wrong, the app should say so!

**Comment by TehShrike** [comment]
Quite right.  This is similar to #13, but it is a different case.  This should be fixed.

**Comment by Vehmloewff** [comment]
Also if the url is wrong, it should stop it from being added to the history.

Right now it adds it to the history, and because every time the user moves into the `workbook` state, the app crashes, it is impossible for the user remove the workbook, unless of course they clear their cookies. (Which also removes all the other workbooks saved there.)
