### ISSUE TITLE
Horizontal scroll activated on form focus

### ISSUE THREAD

**Issue by Vehmloewff** [TehShrike/memorize-text-app#6]
When the form is focused at https://memorizetext.com/#/new-deck the window's horizontal scrollbar appears.

**Comment by TehShrike** [comment]
I reproduced this in Firefox as reported.

In Chrome, I always see the horizontal scroll bar!

**Comment by TehShrike** [comment]
Oh also, I noticed that there is a horizontal scroll bar on the sheet selection screen (e.g. when you pick which Bible Acrostic book to work on).  I'm not sure if that's related, or a separate issue.
